# Environment variables
# - HOST_NAME
# - USER_NAME
# - PORT_NUM
# - USER_PASS
# - APP_DIR
# - UWSGI_LOG
# - UWSGI_PID
 
version: 2
jobs:
  deploy_master:
    docker:
      - image: sickp/alpine-sshd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1a:87:f5:b4:33:1d:65:a9:0f:06:f1:88:28:78:69:69"
      - run:
          name: Start master deploy
          command: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -p ${PORT_NUM} "cd ${APP_DIR}; echo ${USER_PASS} | sudo -S git pull; sudo pgrep -f api_uwsgi  | sudo xargs kill -9; sudo uwsgi --ini api/api_uwsgi.ini --daemonize ${UWSGI_LOG} --pidfile ${UWSGI_PID}"
  deploy_stg:
    docker:
      - image: sickp/alpine-sshd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1a:87:f5:b4:33:1d:65:a9:0f:06:f1:88:28:78:69:69"
      - run:
          name: Start stg deploy
          command: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -p ${PORT_NUM} "cd ${APP_DIR}; echo ${USER_PASS} | sudo -S git pull; sudo pgrep -f stg_uwsgi  | sudo xargs kill -9; sudo uwsgi --ini api/stg_uwsgi.ini --daemonize  /var/log/stg_uwsgi.log --pidfile /var/log/stg_uwsgi.pid"

workflows:
  version: 2
  deploy_to_server: 
    jobs: 
      - deploy:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: staging